// Channel key persistence: the channels file (default ~/.dap/channels.json,
// SHARED across all adapters on a machine) maps channel name -> x25519
// keypair {pub,priv}. Possession of the private key IS v1 membership.
// Mirrors omp-extension/src/channels.ts.
import fs from 'node:fs';
import path from 'node:path';
import { b64d, b64e, newX25519Keypair } from './crypto.js';

export interface ChannelKeys {
  pub: string;
  priv: string;
}

/** Fresh channel x25519 keypair — generated by the channel's first user. */
export function newChannelKeypair(): ChannelKeys {
  const kp = newX25519Keypair();
  return { pub: b64e(kp.pub), priv: b64e(kp.priv) };
}

/** Channels file: { "<channel>": { "pub": "<b64>", "priv": "<b64>" } }.
 *  Missing or invalid file = no channels. */
export function loadChannelKeys(file: string): Record<string, ChannelKeys> {
  try {
    const raw = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, Partial<ChannelKeys>>;
    const out: Record<string, ChannelKeys> = {};
    for (const [name, keys] of Object.entries(raw)) {
      if (typeof keys?.pub === 'string' && typeof keys?.priv === 'string') out[name] = { pub: keys.pub, priv: keys.priv };
    }
    return out;
  } catch {
    return {};
  }
}

/** Read-modify-write: keeps the other channels; creates the parent dir
 *  (e.g. ~/.dap) on demand. */
export function persistChannelKeys(file: string, name: string, keys: ChannelKeys): void {
  const all = loadChannelKeys(file);
  all[name] = keys;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(all, null, 2) + '\n');
}

/** A DM whose decrypted text is exactly a channel-invite payload
 *  ({"t":"chankey","channel","pub","priv"}); anything else is regular chat. */
export function parseChankeyInvite(text: string): ChannelKeys & { channel: string } | undefined {
  if (text.charCodeAt(0) !== 0x7b) return undefined; // not JSON — regular chat
  try {
    const v = JSON.parse(text) as { t?: unknown; channel?: unknown; pub?: unknown; priv?: unknown };
    if (v.t !== 'chankey') return undefined;
    if (typeof v.channel !== 'string' || typeof v.pub !== 'string' || typeof v.priv !== 'string') return undefined;
    if (b64d(v.pub).length !== 32 || b64d(v.priv).length !== 32) return undefined;
    return { channel: v.channel, pub: v.pub, priv: v.priv };
  } catch {
    return undefined;
  }
}
