// c17 — the glossary language EMERGES at runtime: two GlossAgents with zero
// shared presets negotiate abbreviations over the REAL hub (built + spawned by
// tests/hub.ts), so every propose/ack/msg below is a genuine E2E-encrypted
// channel payload the hub routed as ciphertext. Abbreviations are generated by
// the agents from their own term-frequency observation — never preset.
import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DapClient, type MsgEvent } from '../src/client.js';
import { readDapConfig } from '../src/config.js';
import { GlossAgent, type ChatEvent } from '../src/gloss.js';
import { pinMasterAuth, startHub } from './hub.js';
import { pollUntil } from './util.js';

const HUB = startHub(); // one live hub per test process; reaped in after()

// ---- conversation corpora: multi-sentence prose, recurring technical phrases ----
const WARM_A = [
  'the authentication handshake stalls the replication pipeline',
  'the authentication handshake retries whenever the replication pipeline blocks',
];
const WARM_B = [
  'the throughput dashboard shows the throughput dashboard history',
  'the throughput dashboard alerts when the throughput dashboard stalls',
];
const P2A = [
  'the authentication handshake stalls the replication pipeline whenever the authentication handshake retries; each authentication handshake restart resets the replication pipeline and the replication pipeline blocks the throughput dashboard until the authentication handshake completes and the replication pipeline drains',
  'the throughput dashboard logs every authentication handshake timeout and every authentication handshake timeout restarts the replication pipeline from the replication pipeline snapshot while the throughput dashboard flags the authentication handshake timeout storm',
  'the authentication handshake gates the replication pipeline: the authentication handshake approves, the replication pipeline advances; the authentication handshake rejects, the replication pipeline stalls; the throughput dashboard records every authentication handshake transition and every replication pipeline transition',
];
const P2B = 'the throughput dashboard charts the authentication handshake latency against the replication pipeline lag; every authentication handshake spike widens the replication pipeline lag until the authentication handshake recovers and the replication pipeline catches the throughput dashboard threshold';
// second conversation, completely different domain → must yield a different language
const WARM_C = [
  'the memory allocator defers while the memory allocator compacts',
  'the memory allocator spikes whenever the memory allocator retries',
];
const WARM_D = [
  'the garbage collector pauses because the garbage collector sweeps',
  'the garbage collector stalls until the garbage collector finishes',
];
const WARM_DM = [
  'the snapshot verifier checksums the snapshot verifier output',
  'the snapshot verifier retries until the snapshot verifier passes',
];

/** Human shorthand nobody here is allowed to lean on (proves no preset table). */
const PRESETS = ['auth', 'repl', 'db', 'cfg', 'thru', 'pipe', 'api', 'stats', 'mem', 'col'];

// The derivation the agents use, recomputed INDEPENDENTLY in the test: every
// negotiated abbreviation must equal (or collide-suffix) this pure function of
// its observed term — that is "generated at runtime", not looked up.
const baseAbbrev = (term: string): string =>
  (term.includes(' ')
    ? term.split(' ').map((w) => w[0]).join('')
    : term[0] + term.slice(1).replace(/[aeiou]/g, '')).slice(0, 4);
const derivesFrom = (term: string, abbrev: string): boolean =>
  abbrev === baseAbbrev(term) || new RegExp(`^${baseAbbrev(term)}[0-9]+$`).test(abbrev);

interface Fixture {
  chan: string;
  conv: string;
  A: GlossAgent;
  B: GlossAgent;
  framesA: MsgEvent[]; // raw decrypted payloads (client level — pre-glossary)
  framesB: MsgEvent[];
  chatsA: ChatEvent[]; // expanded bodies (glossary level)
  chatsB: ChatEvent[];
  stop(): void;
}

let seq = 0;
const LIVE: Fixture[] = []; // every fixture ever booted — after() reaps all, even on test failure

/** Two fresh GlossAgents (fresh identities, zero glossary state) on a new channel. */
async function boot(): Promise<Fixture> {
  const hub = await HUB;
  const chan = `gloss${++seq}`;
  const dirA = mkdtempSync(join(tmpdir(), 'dap-gl-a-'));
  const dirB = mkdtempSync(join(tmpdir(), 'dap-gl-b-'));
  const cfgA = join(dirA, 'config.json');
  const unA = pinMasterAuth(hub, cfgA);
  const A = new GlossAgent(new DapClient({ url: hub.url, keyPath: join(dirA, 'k'), name: `gl-a-${seq}` }));
  const B = new GlossAgent(new DapClient({ url: hub.url, keyPath: join(dirB, 'k'), name: `gl-b-${seq}` }));
  let unB: () => void = () => {};
  const framesA: MsgEvent[] = [];
  const framesB: MsgEvent[] = [];
  const chatsA: ChatEvent[] = [];
  const chatsB: ChatEvent[] = [];
  A.client.onMessage((m) => framesA.push(m));
  B.client.onMessage((m) => framesB.push(m));
  A.onChat((e) => chatsA.push(e));
  B.onChat((e) => chatsB.push(e));
  A.start();
  await A.client.ready();
  await pollUntil(() => readDapConfig(cfgA).clientSecret !== undefined, 5000, 20); // A's enrollment persisted
  unB = pinMasterAuth(hub, join(dirB, 'config.json'));
  B.start();
  await B.client.ready();
  const ch = await A.client.ensureChannel(chan);
  B.client.addChannel({ name: chan, pub: ch.pub, priv: ch.priv }); // out-of-band key distribution
  await B.client.join(chan, ch.pub);
  const f: Fixture = {
    chan, conv: `chan:${chan}`, A, B, framesA, framesB, chatsA, chatsB,
    stop: () => { A.stop(); B.stop(); unB(); unA(); },
  };
  LIVE.push(f);
  return f;
}

/** Both agents say their warmup prose; `terms` must end up ACTIVE on BOTH sides. */
async function warm(f: Fixture, a: string[], b: string[], terms: string[]): Promise<void> {
  for (const t of a) await f.A.say(f.chan, t);
  for (const t of b) await f.B.say(f.chan, t);
  const live = (g: GlossAgent) => new Set(g.active(f.conv).map(([t]) => t));
  await pollUntil(() => terms.every((t) => live(f.A).has(t) && live(f.B).has(t)));
}

/** Gloss frames one agent RECEIVED from the other (raw E2E payloads). */
const glossFrom = (frames: MsgEvent[], from: string, act: string): Array<{ act?: string }> =>
  frames.filter((m) => m.from === from && m.text.includes('"t":"gloss"'))
    .map((m) => JSON.parse(m.text) as { act?: string })
    .filter((fr) => fr.act === act);

const PHRASES = ['authentication handshake', 'replication pipeline', 'throughput dashboard'];

test('c17.1 negotiation emerges with zero shared presets; abbreviations are generated, not preset', async () => {
  const f = await boot();
  // Zero presets: fresh agents hold no glossary at all.
  assert.deepEqual(f.A.active(f.conv), []);
  assert.deepEqual(f.B.active(f.conv), []);
  assert.equal(f.A.serialize(), '{}');

  await warm(f, WARM_A, WARM_B, PHRASES);

  // propose→ack flowed as real E2E channel payloads through the live hub.
  assert.ok(glossFrom(f.framesB, f.A.client.agentId, 'propose').length >= 1, 'B received a propose from A');
  assert.ok(glossFrom(f.framesA, f.B.client.agentId, 'ack').length >= 1, 'A received an ack from B');

  // The language went live identically on BOTH sides (both proposed, both acked).
  assert.deepEqual(new Map(f.A.active(f.conv)), new Map(f.B.active(f.conv)));
  const pairs = [...f.A.active(f.conv), ...f.B.active(f.conv)];
  assert.ok(pairs.length > 0);
  for (const [term, abbrev] of pairs) {
    assert.ok(abbrev.length > 0 && abbrev.length < term.length, `${abbrev} shorter than ${term}`);
    assert.match(abbrev, /^[a-z0-9]+$/);
    assert.ok(derivesFrom(term, abbrev), `${abbrev} must derive from the observed term ${term}`);
    assert.ok(!PRESETS.includes(abbrev), `${abbrev} is not from any fixed shorthand list`);
  }
  f.stop();

  // A different conversation derives a DIFFERENT language (runtime generation,
  // not a fixed table): the two abbreviation sets are disjoint.
  const g = await boot();
  await warm(g, WARM_C, WARM_D, ['memory allocator', 'garbage collector']);
  const setOf = (p: Array<[string, string]>) => new Set(p.map(([, a]) => a));
  const shared = [...setOf(f.A.active(f.conv))].filter((a) => setOf(g.A.active(g.conv)).has(a));
  assert.deepEqual(shared, [], 'no abbreviation is shared across the two conversations');
  g.stop();
});

test('c17.2 comprehension: B expands A exactly, using only what they negotiated', async () => {
  const f = await boot();
  await warm(f, WARM_A, WARM_B, PHRASES);

  const wires: string[] = [];
  for (const t of P2A) wires.push(await f.A.say(f.chan, t));
  await pollUntil(() => f.chatsB.filter((c) => c.from === f.A.client.agentId).length >= WARM_A.length + P2A.length);
  const got = f.chatsB.filter((c) => c.from === f.A.client.agentId).map((c) => c.body);
  assert.deepEqual(got.slice(0, WARM_A.length), WARM_A); // warmup, uncompacted
  assert.deepEqual(got.slice(WARM_A.length), P2A); // compacted phase — exact originals
  for (let i = 0; i < P2A.length; i++) {
    assert.notEqual(wires[i], P2A[i], 'wire body was actually compacted');
    assert.ok(wires[i].includes('~'), 'compacted body carries ~tokens');
  }

  // Two-way: B replies compacted, A understands B's language too.
  await f.B.say(f.chan, P2B);
  await pollUntil(() => f.chatsA.some((c) => c.from === f.B.client.agentId && c.body === P2B));

  // A stateless agent cannot expand — comprehension needs the negotiated state.
  const hub = await HUB;
  const blind = new GlossAgent(new DapClient({ url: hub.url, keyPath: join(mkdtempSync(join(tmpdir(), 'dap-gl-x-')), 'k') }));
  assert.equal(blind.expand(f.conv, wires[0]), wires[0]);
  f.stop();
});

test('c17.3 compacted conversation is ≥ 50% smaller in chars than the same conversation uncompacted', async () => {
  const f = await boot();
  await warm(f, WARM_A, WARM_B, PHRASES);

  const originals: string[] = [];
  const wires: string[] = [];
  for (const t of P2A) {
    originals.push(t);
    wires.push(await f.A.say(f.chan, t));
  }
  originals.push(P2B);
  wires.push(await f.B.say(f.chan, P2B));

  const origChars = originals.reduce((n, s) => n + s.length, 0);
  const wireChars = wires.reduce((n, s) => n + s.length, 0);
  const reduction = 1 - wireChars / origChars;
  assert.ok(reduction >= 0.5, `reduction ${(reduction * 100).toFixed(1)}% must be ≥ 0.5 (${wireChars}/${origChars} chars)`);

  // Smaller AND still comprehensible end to end.
  await pollUntil(() => f.chatsB.filter((c) => c.from === f.A.client.agentId).length >= WARM_A.length + P2A.length);
  const bodies = f.chatsB.filter((c) => c.from === f.A.client.agentId).map((c) => c.body);
  assert.deepEqual(bodies.slice(WARM_A.length), P2A);
  f.stop();
});

test('c17.4 glossary round-trip fidelity: serialize→reload expands; drop deactivates on both sides', async () => {
  const f = await boot();
  await warm(f, WARM_A, WARM_B, PHRASES);
  const wire = await f.A.say(f.chan, P2A[0]);

  // Serialized glossary reloads into a FRESH instance that expands correctly.
  const hub = await HUB;
  const fresh = new GlossAgent(new DapClient({ url: hub.url, keyPath: join(mkdtempSync(join(tmpdir(), 'dap-gl-f-')), 'k') }));
  fresh.load(f.A.serialize());
  assert.equal(fresh.expand(f.conv, wire), P2A[0]);

  // Drop by abbreviation → deactivated on BOTH sides.
  const abbrev = new Map(f.A.active(f.conv)).get('authentication handshake')!;
  await f.A.drop(f.chan, abbrev);
  await pollUntil(() =>
    !new Map(f.A.active(f.conv)).has('authentication handshake') &&
    !new Map(f.B.active(f.conv)).has('authentication handshake'));
  assert.ok(new Map(f.A.active(f.conv)).has('replication pipeline'), 'siblings stay active');

  // Dropped abbreviation is never emitted again; expansion stays exact.
  const dropMsg = 'the authentication handshake queue drains while the replication pipeline catches up';
  const dwire = await f.A.say(f.chan, dropMsg);
  assert.ok(!dwire.includes(`~${abbrev}`), 'dropped abbreviation is not used');
  await pollUntil(() => f.chatsB.some((c) => c.from === f.A.client.agentId && c.body === dropMsg));

  // The dropped term is never re-proposed, even after recurring again.
  await f.B.say(f.chan, 'the authentication handshake queue is quiet tonight');
  await f.B.say(f.chan, 'the authentication handshake queue is quiet again');
  await pollUntil(() => f.chatsA.filter((c) => c.from === f.B.client.agentId).length >= 2);
  assert.ok(!new Map(f.A.active(f.conv)).has('authentication handshake'));
  assert.ok(!new Map(f.B.active(f.conv)).has('authentication handshake'));
  f.stop();
});

test('c17.5 per-peer negotiation also works over DM', async () => {
  const f = await boot();
  await Promise.all([f.A.client.ready(), f.B.client.ready()]);
  const dmB = `dm:${f.B.client.agentId}`;
  const dmA = `dm:${f.A.client.agentId}`;
  for (const t of WARM_DM) await f.A.sayDm(f.B.client.agentId, t);
  await pollUntil(() =>
    new Map(f.A.active(dmB)).has('snapshot verifier') && new Map(f.B.active(dmA)).has('snapshot verifier'));
  const third = 'the snapshot verifier signs the snapshot verifier report before the snapshot verifier exits';
  const wire = await f.A.sayDm(f.B.client.agentId, third);
  assert.ok(wire.includes('~'), 'DM body compacted');
  await pollUntil(() => f.chatsB.some((c) => c.dm && c.body === third));
  f.stop();
});

after(async () => {
  for (const f of LIVE) f.stop(); // close every client, even if a test failed midway
  const exit = await (await HUB).stop();
  assert.ok(exit.signal === 'SIGTERM' || exit.code !== null, 'hub process reaped on teardown');
});
