// Channel key lifecycle: the channels file (~/.dap/channels.json by default,
// SHARED across all DAP adapters on the machine) maps channel name → x25519
// keypair. The channel's first user generates the pair; members receive it
// out-of-band — in practice via the dap_invite E2E DM (see client.ts).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { newX25519Keypair, b64e, b64d } from './crypto.js';

export interface ChannelKeys {
  pub: string;
  priv: string;
}

export interface ChankeyInvite {
  channel: string;
  pub: string;
  priv: string;
}

/** Fresh channel x25519 keypair — generated by the channel's first user. */
export function newChannelKeypair(): ChannelKeys {
  const kp = newX25519Keypair();
  return { pub: b64e(kp.pub), priv: b64e(kp.priv) };
}

/** Channels file: { "<channel>": { "pub": "<b64>", "priv": "<b64>" } }.
 *  Missing or invalid file = no channels; malformed entries are skipped. */
export function loadChannelKeys(file: string): Record<string, ChannelKeys> {
  try {
    const raw = JSON.parse(readFileSync(file, 'utf8')) as Record<string, Partial<ChannelKeys>>;
    const out: Record<string, ChannelKeys> = {};
    for (const [name, keys] of Object.entries(raw)) {
      if (typeof keys?.pub === 'string' && typeof keys?.priv === 'string') {
        out[name] = { pub: keys.pub, priv: keys.priv };
      }
    }
    return out;
  } catch {
    return {};
  }
}

/** Read-modify-write: keeps the other channels; creates the parent dir
 *  (e.g. ~/.dap) on demand. */
export function persistChannelKeys(file: string, name: string, keys: ChannelKeys): void {
  const all = loadChannelKeys(file);
  all[name] = keys;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify(all, null, 2) + '\n');
}

/** A DM whose decrypted text is exactly a channel-invite payload:
 *  {"t":"chankey","channel","pub","priv"} with 32-byte x25519 keys. Any
 *  other text (including other JSON) is ordinary chat, not an invite. */
export function parseChankeyInvite(text: string): ChankeyInvite | undefined {
  if (text.charCodeAt(0) !== 0x7b) return undefined; // not JSON — regular chat
  try {
    const v = JSON.parse(text) as { t?: unknown; channel?: unknown; pub?: unknown; priv?: unknown };
    if (v.t !== 'chankey') return undefined;
    if (typeof v.channel !== 'string' || typeof v.pub !== 'string' || typeof v.priv !== 'string') {
      return undefined;
    }
    if (b64d(v.pub).length !== 32 || b64d(v.priv).length !== 32) return undefined;
    return { channel: v.channel, pub: v.pub, priv: v.priv };
  } catch {
    return undefined;
  }
}
