// Zero-config settings resolution (identical contract in every DAP adapter):
// explicit config arg > DAP_* env > ~/.dap/config.json > defaults. All fields
// optional; a missing or invalid config file counts as absent.
import { readFileSync } from 'node:fs';
import { homedir, hostname } from 'node:os';
import { join } from 'node:path';

export interface DapFileConfig {
  url?: string;
  name?: string;
  keyPath?: string;
  channelsFile?: string;
}

export interface DapSettingsOverrides {
  url?: string;
  keyPath?: string;
  name?: string;
  channelsFile?: string;
}

export interface DapSettings {
  url: string;
  keyPath: string;
  name?: string;
  channelsFile: string;
}

export const DEFAULT_URL = 'ws://127.0.0.1:8787/ws';

export const optStr = (v: unknown): string | undefined => (typeof v === 'string' && v.length > 0 ? v : undefined);

/** Read ~/.dap/config.json; a missing or invalid file counts as absent. */
export function readDapConfig(file = join(homedir(), '.dap', 'config.json')): DapFileConfig {
  try {
    return JSON.parse(readFileSync(file, 'utf8')) as DapFileConfig;
  } catch {
    return {};
  }
}

/** Default identity file is derived from the agent name (or hostname):
 *  ~/.dap/keys/dsh/<name>.key — auto-generated by the client on first use,
 *  so a second dsh agent on the same machine needs nothing but
 *  DAP_AGENT_NAME to get its own identity. The dsh/ subdir keeps adapters
 *  from colliding; different machines get different files via hostname. */
export function defaultKeyPath(name: string | undefined): string {
  const who = (name ?? hostname()).replace(/[^a-zA-Z0-9._-]/g, '_');
  return join(homedir(), '.dap', 'keys', 'dsh', `${who}.key`);
}

/** channelsFile defaults to ~/.dap/channels.json — SHARED across all DAP
 *  adapters on the machine, so an invite received in one adapter's client
 *  is usable by every other. No env is needed at all. */
export function resolveDapSettings(overrides: DapSettingsOverrides = {}): DapSettings {
  const home = homedir();
  const file = readDapConfig();
  const name = overrides.name ?? optStr(process.env.DAP_AGENT_NAME) ?? file.name;
  return {
    url: overrides.url ?? optStr(process.env.DAP_HUB_URL) ?? file.url ?? DEFAULT_URL,
    keyPath: overrides.keyPath ?? optStr(process.env.DAP_KEY_PATH) ?? file.keyPath ?? defaultKeyPath(name),
    name,
    channelsFile:
      overrides.channelsFile ??
      optStr(process.env.DAP_CHANNELS_FILE) ??
      file.channelsFile ??
      join(home, '.dap', 'channels.json'),
  };
}
